### PR TITLE
Re-added advantage kit for shooter

### PR DESCRIPTION
**Pull request by ChaoticChaosTheGreat**
The newest merge that implemented shooter simulation has completely rewritten my original code and removed advantage kit. This is to just re-add the advantage kit.

### CODE REVIEW

**Review by ThatXliner — APPROVED** [review]

**Review by 3LucasZ — CHANGES_REQUESTED** [review]
Sorry, I removed AdvantageKit since it was breaking sim and spitting tons of error logs. It doesn't look like the ShooterIO class is doing anything in the code though? Are you just assigning it some attributes? Are we ever going to interact with its methods at some point? VSCode highlighted and said it wasn't being used and could be safely removed, so I just commented it out. Also, why did you clamp the voltage to 16? Is that better than 12? Thanks.

**Comment by ChaoticChaosTheGreat** [comment]
> Sorry, I removed AdvantageKit since it was breaking sim and spitting tons of error logs. It doesn't look like the ShooterIO class is doing anything in the code though? Are you just assigning it some attributes? Are we ever going to interact with its methods at some point? VSCode highlighted and said it wasn't being used and could be safely removed, so I just commented it out. Also, why did you clamp the voltage to 16? Is that better than 12? Thanks.

Voltage is clamped to 16 for more power theoretically since the motor can go up to 16 volts. ShooterIO is again just for advantage kit, and setting the pid values inside there. I honestly don't really know why it needs them but it was working in the KitBot.

**Comment by ChaoticChaosTheGreat** [comment]
Also @3LucasZ is there a reason we removed the feedforward in the shooter subsystem? The TalonFX docs said it was the best to combine both the feedforward and feedback instead o just using one.

**Comment by 3LucasZ** [comment]
Good point. For the Robot.isReal, you should add feedforward and bring back the old constants, that's a good idea. I tuned the PID to work for sim, so removed the feedforward. Maybe can make a new PID constants just for sim to be separate from real robot. Might be annoying/redundant though.

**Comment by 3LucasZ** [comment]
Thank you for the 16V fix :). I didn't do know that prior!.

**Review by 3LucasZ — APPROVED** [review]
Thank you for adding this back. Apologies that I commented it out. If it breaks sim again, I will have to comment  it out again though. Please make sure it doesnt break sim before we merge.

**Comment by 3LucasZ** [comment]
Squash and merge, when you are ready buddy.

**Pull request merged**
