### PR TITLE
Shuffleboard subsystem implementations

### PR DESCRIPTION
**Pull request by ChaoticChaosTheGreat**

### CODE REVIEW

**Comment by ChaoticChaosTheGreat** [comment]
Fixed oblog stuff.

**Review by realjoshuau — APPROVED** [review]
lgtm, test w robot and i'll merge

**Comment by 3LucasZ** [comment]
^ Please send video of this working in sim
Would like to see the Shuffleboard layout working.
here is an example of what we made last year. Your video should show something like this.
Screenshot 2023-01-12 at 5 12 10 PM

**Review by realjoshuau — APPROVED** [review]
lgtm

**Comment by ChaoticChaosTheGreat** [comment]
dkljasbdfjcbskfjkasjdfsduhasildhfiosdwaw yo merge so every branch has more merge conflicts

**Review by realjoshuau — APPROVED** [review]
lgtm

**Pull request merged**
